### ISSUE TITLE
which version node & npm & yarn used in project ?

### ISSUE THREAD

**Issue by todokku** [sunghye-on/Utube#1]
Hi sungHyeon,
which version node & npm & yarn used in project ?
waiting for your response
finest regards
goodbye

**Comment by sunghye-on** [comment]
nice to meet you. I'm sunghyeon.
I checked your GitHub account's repository and over 550 were forked.
I doubt you ask for node version and npm version
 
Do you make app.json file for Heroku deploy and get paid? Or will you tell me how to make it?
 
-----Original Message-----

**Comment by todokku** [comment]
hello again sunghyeon , nice to meet you 2.
i can make app.json file for deploy to heroku easily , but at first you must tell me your node , npm & yarn version used in project because must set in app.json or package.json with this format :
https://devcenter.heroku.com/articles/nodejs-support
waiting for your response
finest regards
goodbye
